// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Linq2GraphQL.Generator.Templates.Interface
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class InterfaceTemplate : InterfaceTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Text.Json;\r\nusing System.Text.Json.Nodes;\r\nusing Syst" +
                    "em.Text.Json.Serialization;\r\nusing Linq2GraphQL.Client;\r\nusing Linq2GraphQL.Clie" +
                    "nt.Converters;\r\n\r\nnamespace ");
            
            #line 10 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n/// <summary>\r\n/// Extension methods for ");
            
            #line 13 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.Name));
            
            #line default
            #line hidden
            this.Write(" interface type casting\r\n/// </summary>\r\npublic static class ");
            
            #line 15 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.Name));
            
            #line default
            #line hidden
            this.Write("Extensions\r\n{\r\n");
            
            #line 17 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
 foreach (var field in implementedBy) { 
            
            #line default
            #line hidden
            this.Write("    /// <summary>\r\n    /// Casts ");
            
            #line 19 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.Name));
            
            #line default
            #line hidden
            this.Write(" to ");
            
            #line 19 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field));
            
            #line default
            #line hidden
            this.Write(" if the runtime type matches\r\n    /// </summary>\r\n    /// <param name=\"value\">The" +
                    " interface value to cast</param>\r\n    /// <returns>");
            
            #line 22 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field));
            
            #line default
            #line hidden
            this.Write(" instance or null if type doesn\'t match</returns>\r\n    [GraphInterface]\r\n    publ" +
                    "ic static ");
            
            #line 24 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 24 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field));
            
            #line default
            #line hidden
            this.Write("(this ");
            
            #line 24 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.Name));
            
            #line default
            #line hidden
            this.Write(" value)\r\n    {\r\n        if (value.__TypeName == \"");
            
            #line 26 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field));
            
            #line default
            #line hidden
            this.Write("\")\r\n        {\r\n            return (");
            
            #line 28 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field));
            
            #line default
            #line hidden
            this.Write(")value;\r\n        }\r\n        return null;\r\n    }\r\n\r\n");
            
            #line 33 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n/// <summary>\r\n/// JSON converter for ");
            
            #line 37 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.Name));
            
            #line default
            #line hidden
            this.Write(" interface deserialization\r\n/// </summary>\r\ninternal class ");
            
            #line 39 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInterfaceConverterName()));
            
            #line default
            #line hidden
            this.Write(" : InterfaceJsonConverter<");
            
            #line 39 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.Name));
            
            #line default
            #line hidden
            this.Write(@">
{
    /// <summary>
    /// Deserializes JSON to the appropriate concrete type based on __typename
    /// </summary>
    /// <param name=""typeName"">The GraphQL type name from __typename field</param>
    /// <param name=""json"">The JSON object to deserialize</param>
    /// <returns>Deserialized instance of the appropriate concrete type</returns>
    public override ");
            
            #line 47 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.Name));
            
            #line default
            #line hidden
            this.Write(" Deserialize(string typeName, JsonObject json) => typeName switch\r\n    {\r\n");
            
            #line 49 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
 foreach (var field in implementedBy) { 
            
            #line default
            #line hidden
            this.Write("        \"");
            
            #line 50 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field));
            
            #line default
            #line hidden
            this.Write("\" => json.Deserialize<");
            
            #line 50 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field));
            
            #line default
            #line hidden
            this.Write(">(),\r\n");
            
            #line 51 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        _ => json.Deserialize<");
            
            #line 52 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInterfaceConcreteName()));
            
            #line default
            #line hidden
            this.Write(">()\r\n    };\r\n}\r\n\r\n/// <summary>\r\n/// GraphQL interface ");
            
            #line 57 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.Name));
            
            #line default
            #line hidden
            this.Write(" with all common fields\r\n/// </summary>\r\n[JsonConverter(typeof(");
            
            #line 59 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInterfaceConverterName()));
            
            #line default
            #line hidden
            this.Write("))]\r\npublic interface ");
            
            #line 60 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 60 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.GetInterfacesString()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 62 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
 foreach (var field in classType.AllFields) { 
    var coreType = field.CoreType; 
            
            #line default
            #line hidden
            this.Write("    /// <summary>\r\n    /// ");
            
            #line 65 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" field from GraphQL schema\r\n    /// </summary>\r\n    [GraphQLMember(\"");
            
            #line 67 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\")]\r\n    ");
            
            #line 68 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(coreType.CSharpTypeDefinition));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 68 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.CSharpName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n\r\n");
            
            #line 70 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    /// <summary>\r\n    /// GraphQL __typename field for runtime type resolution\r\n" +
                    "    /// </summary>\r\n    [GraphQLMember(\"__typename\")]\r\n    string __TypeName { g" +
                    "et; set; }\r\n}\r\n\r\n/// <summary>\r\n/// Concrete implementation of ");
            
            #line 79 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.Name));
            
            #line default
            #line hidden
            this.Write(" interface for fallback deserialization\r\n/// </summary>\r\ninternal class ");
            
            #line 81 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInterfaceConcreteName()));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 81 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classType.Name));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 83 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
 foreach (var field in classType.AllFields) { 
    var coreType = field.CoreType; 
            
            #line default
            #line hidden
            this.Write("    /// <summary>\r\n    /// ");
            
            #line 86 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" field from GraphQL schema\r\n    /// </summary>\r\n    [GraphQLMember(\"");
            
            #line 88 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\")]\r\n    public ");
            
            #line 89 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(coreType.CSharpTypeDefinition));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 89 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.CSharpName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n\r\n");
            
            #line 91 "C:\Data\Linq2GraphQL.Client-1\src\Linq2GraphQL.Generator\Templates\Interface\InterfaceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    /// <summary>\r\n    /// GraphQL __typename field for runtime type resolution\r\n" +
                    "    /// </summary>\r\n    [GraphQLMember(\"__typename\")]\r\n    public string __TypeN" +
                    "ame { get; set; }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class InterfaceTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
