name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Pack Linq2GraphQL.Client nugets
      run: dotnet pack src/Linq2GraphQL.Client/Linq2GraphQL.Client.csproj -c Release --no-build --output . -p:Version=${GITHUB_REF##*/v}
    
